on:
  push:
    branches:
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test backend
        run: docker compose build
      - name: Run backend tests
        run: docker compose run --rm backend pytest